void nHitInvalid()
{
//=========Macro generated from canvas: c/c
//=========  (Tue Nov 16 15:24:25 2021) by ROOT version6.10/04
   TCanvas *c = new TCanvas("c", "c",754,194,800,756);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   c->Range(-1.086427,-0.1181191,5.304321,0.8467414);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetTickx(1);
   c->SetTicky(1);
   c->SetLeftMargin(0.17);
   c->SetRightMargin(0.04761905);
   c->SetTopMargin(0.07152683);
   c->SetBottomMargin(0.1224209);
   c->SetFrameFillStyle(0);
   c->SetFrameLineWidth(3);
   c->SetFrameBorderMode(0);
   c->SetFrameFillStyle(0);
   c->SetFrameLineWidth(3);
   c->SetFrameBorderMode(0);
   
   TH1F *usednHitInvalidTrack__47 = new TH1F("usednHitInvalidTrack__47","nHitInvalid",5,0,5);
   usednHitInvalidTrack__47->SetBinContent(1,0.7403487);
   usednHitInvalidTrack__47->SetBinContent(2,0.2289518);
   usednHitInvalidTrack__47->SetBinContent(3,0.02914444);
   usednHitInvalidTrack__47->SetBinContent(4,0.001507263);
   usednHitInvalidTrack__47->SetBinContent(5,4.78038e-05);
   usednHitInvalidTrack__47->SetBinContent(6,1.283324e-06);
   usednHitInvalidTrack__47->SetBinError(1,0.0003446206);
   usednHitInvalidTrack__47->SetBinError(2,0.000191644);
   usednHitInvalidTrack__47->SetBinError(3,6.837556e-05);
   usednHitInvalidTrack__47->SetBinError(4,1.554954e-05);
   usednHitInvalidTrack__47->SetBinError(5,2.7692e-06);
   usednHitInvalidTrack__47->SetBinError(6,4.537234e-07);
   usednHitInvalidTrack__47->SetEntries(6233822);
   usednHitInvalidTrack__47->SetDirectory(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   usednHitInvalidTrack__47->SetLineColor(ci);
   usednHitInvalidTrack__47->SetLineWidth(3);
   usednHitInvalidTrack__47->GetXaxis()->SetLabelFont(42);
   usednHitInvalidTrack__47->GetXaxis()->SetLabelSize(0.05);
   usednHitInvalidTrack__47->GetXaxis()->SetTitleSize(0.05);
   usednHitInvalidTrack__47->GetXaxis()->SetTickLength(0.05);
   usednHitInvalidTrack__47->GetXaxis()->SetTitleFont(42);
   usednHitInvalidTrack__47->GetYaxis()->SetTitle("a.u.");
   usednHitInvalidTrack__47->GetYaxis()->SetLabelFont(42);
   usednHitInvalidTrack__47->GetYaxis()->SetLabelSize(0.05);
   usednHitInvalidTrack__47->GetYaxis()->SetTitleSize(0.06);
   usednHitInvalidTrack__47->GetYaxis()->SetTickLength(0.05);
   usednHitInvalidTrack__47->GetYaxis()->SetTitleOffset(0);
   usednHitInvalidTrack__47->GetYaxis()->SetTitleFont(42);
   usednHitInvalidTrack__47->GetZaxis()->SetLabelFont(42);
   usednHitInvalidTrack__47->GetZaxis()->SetLabelSize(0.035);
   usednHitInvalidTrack__47->GetZaxis()->SetTitleSize(0.035);
   usednHitInvalidTrack__47->GetZaxis()->SetTitleFont(42);
   usednHitInvalidTrack__47->Draw("EHIST");
   
   TH1F *usednHitInvalidTrack__48 = new TH1F("usednHitInvalidTrack__48","nHitInvalid",5,0,5);
   usednHitInvalidTrack__48->SetBinContent(1,0.7419076);
   usednHitInvalidTrack__48->SetBinContent(2,0.2275735);
   usednHitInvalidTrack__48->SetBinContent(3,0.02899507);
   usednHitInvalidTrack__48->SetBinContent(4,0.00148006);
   usednHitInvalidTrack__48->SetBinContent(5,4.379453e-05);
   usednHitInvalidTrack__48->SetBinContent(6,1.628049e-06);
   usednHitInvalidTrack__48->SetBinError(1,0.0003475431);
   usednHitInvalidTrack__48->SetBinError(2,0.000192484);
   usednHitInvalidTrack__48->SetBinError(3,6.870619e-05);
   usednHitInvalidTrack__48->SetBinError(4,1.552292e-05);
   usednHitInvalidTrack__48->SetBinError(5,2.670199e-06);
   usednHitInvalidTrack__48->SetBinError(6,5.148344e-07);
   usednHitInvalidTrack__48->SetEntries(6142330);
   usednHitInvalidTrack__48->SetDirectory(0);

   ci = TColor::GetColor("#ff0000");
   usednHitInvalidTrack__48->SetLineColor(ci);
   usednHitInvalidTrack__48->SetLineWidth(3);
   usednHitInvalidTrack__48->GetXaxis()->SetLabelFont(42);
   usednHitInvalidTrack__48->GetXaxis()->SetLabelSize(0.035);
   usednHitInvalidTrack__48->GetXaxis()->SetTitleSize(0.035);
   usednHitInvalidTrack__48->GetXaxis()->SetTitleFont(42);
   usednHitInvalidTrack__48->GetYaxis()->SetTitle("a.u.");
   usednHitInvalidTrack__48->GetYaxis()->SetLabelFont(42);
   usednHitInvalidTrack__48->GetYaxis()->SetLabelSize(0.035);
   usednHitInvalidTrack__48->GetYaxis()->SetTitleSize(0.035);
   usednHitInvalidTrack__48->GetYaxis()->SetTitleOffset(0);
   usednHitInvalidTrack__48->GetYaxis()->SetTitleFont(42);
   usednHitInvalidTrack__48->GetZaxis()->SetLabelFont(42);
   usednHitInvalidTrack__48->GetZaxis()->SetLabelSize(0.035);
   usednHitInvalidTrack__48->GetZaxis()->SetTitleSize(0.035);
   usednHitInvalidTrack__48->GetZaxis()->SetTitleFont(42);
   usednHitInvalidTrack__48->Draw("EHISTSAME");
   
   TLegend *leg = new TLegend(0.74,0.7,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextFont(62);
   leg->SetTextSize(0.04);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("NULL","Campaign","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(22);
   entry->SetTextFont(42);
   entry=leg->AddEntry("usednHitInvalidTrack","Data","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("usednHitInvalidTrack","MC","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   leg = new TLegend(0.74,0.7,0.9,0.88,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetTextFont(62);
   leg->SetTextSize(0.04);
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   entry=leg->AddEntry("NULL","Campaign","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextAlign(22);
   entry->SetTextFont(42);
   entry=leg->AddEntry("usednHitInvalidTrack","Data","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#0000ff");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("usednHitInvalidTrack","MC","lpf");
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#ff0000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(3);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(1);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.74,0.94,"0T cosmic rays");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetTextSize(0.039);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.27,0.94,"Internal Work");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetTextSize(0.039);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.17,0.94,"CMS");
tex->SetNDC();
   tex->SetLineWidth(2);
   tex->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
